<?php

if (class_exists(OC::class)) {
  include \OC::$SERVERROOT . '/version.php';
}
else {
  include __DIR__ .  '/../version.php';
}

$CONFIG = array (
  // This is messy, but it works
  'version' => implode(".", $OC_Version),
  'installed' => true,
);

if (
  file_exists($this->configDir . 'CAN_INSTALL') ||
  file_exists($this->configDir . 'autoconfig.php')
) {
  $CONFIG['installed'] = false;
}

/**
 * Default Parameters
 *
 * These parameters are configured by the Nextcloud installer, and are required
 * for your Nextcloud server to operate.
 */


/**
 * This is a unique identifier for your Nextcloud installation, created
 * automatically by the installer. This example is for documentation only,
 * and you should never use it because it will not work. A valid ``instanceid``
 * is created when you install Nextcloud.
 *
 * 'instanceid' => 'd3c944a9a',
 */
$instanceid = getenv('NEXTCLOUD_INSTANCE_ID');
if ($instanceid !== false) {
  $CONFIG['instanceid'] = $instanceid;
}

 /**
  * The salt used to hash all passwords, auto-generated by the Nextcloud
  * installer. (There are also per-user salts.) If you lose this salt you lose
  * all your passwords. This example is for documentation only, and you should
  * never use it.
  *
  * @deprecated This salt is deprecated and only used for legacy-compatibility,
  * developers should *NOT* use this value for anything nowadays.
  *
  * 'passwordsalt' => 'd3c944a9af095aa08f',
 */
$passwordsalt = getenv('NEXTCLOUD_PASSWORD_SALT');
if ($passwordsalt !== false) {
  $CONFIG['passwordsalt'] = $passwordsalt;
}

/**
 * Your list of trusted domains that users can log into. Specifying trusted
 * domains prevents host header poisoning. Do not remove this, as it performs
 * necessary security checks.
 * You can specify:
 *
 * - the exact hostname of your host or virtual host, e.g. demo.example.org.
 * - the exact hostname with permitted port, e.g. demo.example.org:443.
 *   This disallows all other ports on this host
 * - use * as a wildcard, e.g. ubos-raspberry-pi*.local will allow
 *   ubos-raspberry-pi.local and ubos-raspberry-pi-2.local
 * - the IP address with or without permitted port, e.g. [2001:db8::1]:8080
 *   Using TLS certificates where commonName=<IP address> is deprecated
 */
$trusted_domains = getenv('NEXTCLOUD_TRUSTED_DOMAINS');
if ($trusted_domains !== false) {
  $CONFIG['trusted_domains'] = explode(',', $trusted_domains);
}

/**
 * Where user files are stored. The SQLite database is also stored here, when
 * you use SQLite.
 *
 * Default to ``data/`` in the Nextcloud directory.
 */
$datadirectory = getenv('NEXTCLOUD_DATA_DIR');
if ($datadirectory !== false) {
  $CONFIG['datadirectory'] = $datadirectory;
}

/**
 * The current version number of your Nextcloud installation. This is set up
 * during installation and update, so you shouldn't need to change it.
 */
$version = getenv('NEXTCLOUD_VERSION');
if ($version !== false) {
  $CONFIG['version'] = $version;
}

/**
 * Indicates whether the Nextcloud instance was installed successfully; ``true``
 * indicates a successful installation, and ``false`` indicates an unsuccessful
 * installation.
 *
 * Defaults to ``false``
 */
$installed = getenv('NEXTCLOUD_INSTALLED');
if ($installed !== false) {
  $CONFIG['installed'] = $installed;
}

/**
 * Secret used by Nextcloud for various purposes, e.g. to encrypt data. If you
 * lose this string there will be data corruption.
 */
$secret = getenv('NEXTCLOUD_SECRET');
if ($secret !== false) {
  $CONFIG['secret'] = $secret;
}

/**
 * Where Appdata files are stored. File previews are stored here. Changing this
 * to a local path dramatically improves performance when using S3/object
 * storage.
 *
 * Default to ``data/appdata_[instance_id]`` in the Nextcloud web root.
 */
$appdataroot = getenv('NEXTCLOUD_APPDATAROOT');
if ($appdataroot !== false) {
  $CONFIG['appdataroot'] = $appdataroot;
}
